//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalDictionary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalDictionary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abandon
        ///v./n.放弃；放纵
        ///abash
        ///v.使害羞，使尴尬
        ///abate
        ///v.减轻，减少
        ///abbreviate
        ///v.缩短；缩写
        ///abdicate
        ///v.退位，辞职，放弃
        ///aberrant
        ///a.越轨的；异常的
        ///aberration
        ///n.离开正路，脱离常轨；变形
        ///abet
        ///v.教唆，鼓励，帮助
        ///abeyance
        ///n.中止，搁置
        ///abhor
        ///v.憎恨，嫌恶
        ///abhorrent
        ///a.可恨的，讨厌的
        ///abide
        ///v.容忍，忍受
        ///abject
        ///a.极可怜的;卑下的
        ///abjure
        ///v.发誓放弃
        ///ablution
        ///n.(宗教的)净礼，沐浴
        ///abnegate
        ///v.否认，放弃
        ///abolish
        ///v.废止，废除(法律、制度、习俗等)
        ///abolition
        ///n.废除，革除
        ///abominate
        ///v.痛恨；厌恶
        ///aboveboard
        ///a./adv.光明正大的(地)
        ///abrade
        ///v.磨损，磨小
        ///abrasion
        ///n.表面磨损
        ///abrasive
        ///a.磨损的；生硬粗暴的
        ///abreast
        ///adv.并列，并排
        ///abridge
        ///v.删减；缩短
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gre {
            get {
                return ResourceManager.GetString("gre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abandon
        ///vt. 放弃
        ///abandoned
        ///a.被抛弃的
        ///abashed
        ///a.羞愧的局促不安的
        ///abate
        ///vt.减少
        ///abdicate
        ///vt.放弃权力
        ///abduct
        ///vi.绑架,诱拐
        ///abhor
        ///n.憎恶
        ///abhorrent
        ///a.嫌恶的
        ///abide
        ///vt.遵守 vt.忍受
        ///ability
        ///n.能力
        ///abject
        ///a. 不幸的,可怜的,悲惨的
        ///ablaze
        ///a.闪耀的
        ///ablution
        ///n.沐浴
        ///abnormal
        ///a.异常
        ///abolish
        ///vt.废除，取消
        ///aboriginal
        ///n.土著 a.土著的
        ///aborigine
        ///n.土著
        ///abortive
        ///a.失败的
        ///abridge
        ///vt.缩短；删节
        ///absenteeism
        ///n. 旷工；旷课
        ///absolute
        ///a.绝对的
        ///absolve
        ///vt.赦免；解除(责任等)
        ///absorb
        ///vt.吸收；并吞
        ///absorbing
        ///a.引人入胜的
        ///abstain
        ///vt.戒绝
        ///abstinence
        ///vt.禁戒；节制
        ///abstract
        ///抽象的
        ///abstraction
        ///n.抽 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string toefl {
            get {
                return ResourceManager.GetString("toefl", resourceCulture);
            }
        }
    }
}
